### ISSUE TITLE
Can't login after update to 0.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vosaocms/vosao#250]
```
Can't login to /cms.

javax.servlet.ServletContext log:  Velocity  [error] Error during error 
template rendering - org.apache.velocity.exception.MethodInvocationException: 
Invocation of method 'get' in  class org.vosao.i18n.MessagesTool threw 
exception java.lang.NoSuchMethodError: 
org.vosao.dao.AbstractDao.setEntityCache(Lorg/vosao/dao/cache/EntityCache;)V at 
layouts/layout.vm[line 78, column 51]
org.apache.velocity.exception.MethodInvocationException: Invocation of method 
'get' in  class org.vosao.i18n.MessagesTool threw exception 
java.lang.NoSuchMethodError: 
org.vosao.dao.AbstractDao.setEntityCache(Lorg/vosao/dao/cache/EntityCache;)V at 
layouts/layout.vm[line 78, column 51]
    at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:351)
    at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:284)
    at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:262)
    at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:342)
    at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:336)
    at org.apache.velocity.Template.merge(Template.java:328)
    at org.apache.velocity.Template.merge(Template.java:235)
    at org.apache.velocity.tools.view.VelocityView.performMerge(VelocityView.java:942)
```

Original issue reported on code.google.com by `kinyelo@gmail.com` on 7 Jul 2010 at 2:54
